// 변경 의도: Instagram 견본 두 페이지의 다국어·안내·실제 메뉴 데이터 렌더링을 통합
(() => {
  const STORAGE_KEY = 'lilliputInstagramPreviewLang';
  const ui = {
    ko:{posts:'게시물',open:'오픈',languages:'언어',bio:'아이와 어른이 함께 쉬어가는 프리미엄 키즈 카페',bioLink:'메뉴판 바로가기 ↗',viewMenu:'메뉴 보기',call:'전화하기',food:'음식',drink:'음료',all:'전체',loading:'메뉴를 불러오는 중입니다…',ingredients:'주요 재료'},
    en:{posts:'posts',open:'opens',languages:'languages',bio:'A premium kids café where children and adults relax together',bioLink:'View our menu ↗',viewMenu:'View menu',call:'Call',food:'Food',drink:'Drink',all:'All',loading:'Loading menu…',ingredients:'Ingredients'},
    ja:{posts:'投稿',open:'開店',languages:'言語',bio:'子どもと大人が一緒にくつろげるプレミアムキッズカフェ',bioLink:'メニューを見る ↗',viewMenu:'メニュー',call:'電話する',food:'フード',drink:'ドリンク',all:'すべて',loading:'メニューを読み込んでいます…',ingredients:'主な材料'},
    zh:{posts:'帖子',open:'开店',languages:'语言',bio:'让孩子与大人一起放松的高端亲子咖啡馆',bioLink:'查看菜单 ↗',viewMenu:'查看菜单',call:'致电',food:'餐食',drink:'饮品',all:'全部',loading:'正在加载菜单…',ingredients:'主要食材'}
  };
  const guide = {
    ko:[['어린이',['기본 이용 시간 2시간','평일 20,000원','주말·공휴일 22,000원','12개월 미만 8,000원 / 8,800원','초과 10분당 2,000원 / 2,200원']],['성인',['1인 1메뉴 주문','음료 또는 음식 선택']],['영업시간',['평일 10:30–20:30','주말·공휴일 10:30–21:00']],['대관 안내',['생일 파티 및 행사 대관','전화로 자세히 안내해 드립니다','02-515-9633']]],
    en:[['Children',['Basic use: 2 hours','Weekdays: KRW 20,000','Weekends & holidays: KRW 22,000','Under 12 months: KRW 8,000 / 8,800','Overtime per 10 min: KRW 2,000 / 2,200']],['Adults',['One menu item per adult','Choose a drink or food']],['Hours',['Weekdays 10:30–20:30','Weekends & holidays 10:30–21:00']],['Private Events',['Birthday parties and events','Call us for details','02-515-9633']]],
    ja:[['お子さま',['基本利用時間 2時間','平日 20,000ウォン','週末・祝日 22,000ウォン','12か月未満 8,000 / 8,800ウォン','延長10分 2,000 / 2,200ウォン']],['大人',['お一人様1メニュー','ドリンクまたはフード']],['営業時間',['平日 10:30–20:30','週末・祝日 10:30–21:00']],['貸切案内',['誕生日パーティー・イベント','詳細はお電話でご案内します','02-515-9633']]],
    zh:[['儿童',['基本使用时间 2小时','工作日 20,000韩元','周末及节假日 22,000韩元','未满12个月 8,000 / 8,800韩元','超时每10分钟 2,000 / 2,200韩元']],['成人',['每人需点一份菜单','饮品或餐食']],['营业时间',['工作日 10:30–20:30','周末及节假日 10:30–21:00']],['包场说明',['生日派对及活动包场','详情请致电咨询','02-515-9633']]]
  };
  const categories={PASTA:{ko:'파스타',en:'Pasta',ja:'パスタ',zh:'意面'},PIZZA:{ko:'피자',en:'Pizza',ja:'ピザ',zh:'披萨'},RICE:{ko:'라이스',en:'Rice',ja:'ライス',zh:'米饭'},SALAD:{ko:'샐러드',en:'Salad',ja:'サラダ',zh:'沙拉'},SNACKS:{ko:'스낵',en:'Snacks',ja:'スナック',zh:'小吃'},STEAK:{ko:'스테이크',en:'Steak',ja:'ステーキ',zh:'牛排'},ESPRESSO:{ko:'에스프레소',en:'Espresso',ja:'エスプレッソ',zh:'咖啡'},LATTE:{ko:'라떼',en:'Latte',ja:'ラテ',zh:'拿铁'},'COLD BREW':{ko:'콜드브루',en:'Cold Brew',ja:'コールドブリュー',zh:'冷萃'},'LILLY-CCINO':{ko:'릴리치노',en:'Lilly-ccino',ja:'リリーチーノ',zh:'Lilly-ccino'},SMOOTHIE:{ko:'스무디',en:'Smoothie',ja:'スムージー',zh:'冰沙'},'FRESH JUICE':{ko:'주스',en:'Juice',ja:'ジュース',zh:'果汁'},SODA:{ko:'소다',en:'Soda',ja:'ソーダ',zh:'苏打'},'FRUIT TEA':{ko:'과일차',en:'Fruit Tea',ja:'フルーツティー',zh:'水果茶'},'OTHER BEVERAGE':{ko:'기타',en:'Other',ja:'その他',zh:'其他'},TEA:{ko:'티',en:'Tea',ja:'ティー',zh:'茶'},BEER:{ko:'맥주',en:'Beer',ja:'ビール',zh:'啤酒'},WINE:{ko:'와인',en:'Wine',ja:'ワイン',zh:'葡萄酒'}};
  let language=loadLanguage(), type='foods', category='ALL', data={foods:[],drinks:[]};
  function detect(){const value=(navigator.language||'').toLowerCase();return value.startsWith('ko')?'ko':value.startsWith('ja')?'ja':value.startsWith('zh')?'zh':'en'}
  function loadLanguage(){try{return localStorage.getItem(STORAGE_KEY)||detect()}catch{return detect()}}
  function copyText(){document.documentElement.lang=language;document.querySelectorAll('[data-copy]').forEach(el=>{const value=ui[language][el.dataset.copy];if(value)el.textContent=value});const select=document.querySelector('#language-select');if(select)select.value=language}
  function setupLanguage(){const select=document.querySelector('#language-select');select?.addEventListener('change',()=>{language=select.value;try{localStorage.setItem(STORAGE_KEY,language)}catch{};render()})}
  function renderGuide(){const grid=document.querySelector('#guide-grid'),stories=document.querySelector('#guide-stories');if(!grid||!stories)return;const icons=['🧸','☕','◷','♡'];stories.replaceChildren(...guide[language].map(([title],i)=>{const b=document.createElement('button');b.className='story';b.innerHTML=`<span class="story-ring ${i===0?'gradient':''}"><span class="story-face">${icons[i]}</span></span><span class="story-label">${title}</span>`;b.onclick=()=>document.querySelector(`#guide-${i}`)?.scrollIntoView({behavior:'smooth'});return b}));grid.replaceChildren(...guide[language].map(([title,items],i)=>{const article=document.createElement('article');article.id=`guide-${i}`;article.className=`info-post ${i===0?'featured':''}`;const list=items.map(item=>`<li>${item}</li>`).join('');article.innerHTML=`<span class="post-number">PINNED · 0${i+1}</span><div><h2>${title}</h2><ul>${list}</ul></div>`;return article}))}
  function keyFor(item){return type==='foods'?(item.category||'OTHER'):(item.subcategory||item.category||'OTHER')}
  function labelFor(key){return key==='ALL'?ui[language].all:(categories[key]?.[language]||categories[key]?.en||key)}
  function nameFor(item){return item[`name_${language}`]||item.name_en||item.name_ko||''}
  function priceValue(value){return value==null?'':`${Math.round(Number(value)*1000).toLocaleString('ko-KR')}원`}
  function priceFor(item){if(type==='foods')return priceValue(item.price);if(item.single_price!=null)return priceValue(item.single_price);const hot=priceValue(item.hot_price),ice=priceValue(item.ice_price);return hot&&ice?`HOT ${hot} · ICE ${ice}`:hot||ice}
  function renderMenu(){const feed=document.querySelector('#menu-feed'),chips=document.querySelector('#category-chips');if(!feed||!chips)return;document.querySelectorAll('[data-type]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.type===type)));const source=data[type],keys=['ALL',...new Set(source.map(keyFor).filter(Boolean))];chips.replaceChildren(...keys.map(key=>{const b=document.createElement('button');b.className='chip';b.textContent=labelFor(key);b.setAttribute('aria-pressed',String(category===key));b.onclick=()=>{category=key;renderMenu()};return b}));const visible=category==='ALL'?source:source.filter(item=>keyFor(item)===category);feed.replaceChildren(...visible.map((item,index)=>{const article=document.createElement('article');article.className='menu-post';const ingredients=type==='foods'&&item.ingredients?.length?`${ui[language].ingredients}: ${item.ingredients.join(', ')}`:(item.notes||'');article.innerHTML=`<div class="post-head"><span class="mini-avatar"></span><span class="post-account">lilliput.menu<span>${labelFor(keyFor(item))}</span></span><span class="post-more">•••</span></div><div class="food-visual" data-tone="${index%4}">${item.is_new?'<span class="new-badge">NEW</span>':''}<span class="visual-label">${labelFor(keyFor(item))}</span></div><div class="post-actions"><span>♡</span><span>◯</span><span>⌁</span><span>⌑</span></div><div class="post-copy"><strong>lilliput.menu</strong>${nameFor(item)}<span class="price">${priceFor(item)}</span>${ingredients?`<div class="ingredients">${ingredients}</div>`:''}</div>`;return article}))}
  async function loadMenu(){try{const [foods,drinks]=await Promise.all([fetch('/src/data/menu/menu_foods.json').then(r=>r.json()),fetch('/src/data/menu/menu_drinks.json').then(r=>r.json())]);data={foods,drinks};renderMenu()}catch(error){console.error(error);document.querySelector('#menu-feed').innerHTML='<div class="loading">Menu unavailable</div>'}}
  function setupTypes(){document.querySelectorAll('[data-type]').forEach(button=>button.addEventListener('click',()=>{type=button.dataset.type;category='ALL';renderMenu()}))}
  function render(){copyText();document.body.dataset.page==='guide'?renderGuide():renderMenu()}
  setupLanguage();copyText();if(document.body.dataset.page==='guide')renderGuide();else{setupTypes();loadMenu()}
})();
