"""create waiting table

Revision ID: 975ccf4e8b5c
Revises: 
Create Date: 2025-08-12 21:18:02.085588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975ccf4e8b5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('called', sa.Boolean(), nullable=False),
    sa.Column('visited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiting_id'), 'waiting', ['id'], unique=False)
    op.create_index(op.f('ix_waiting_phone'), 'waiting', ['phone'], unique=False)
    op.create_index('uq_waiting_phone_open', 'waiting', ['phone'], unique=False, postgresql_where=sa.text('NOT visited'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_waiting_phone_open', table_name='waiting', postgresql_where=sa.text('NOT visited'))
    op.drop_index(op.f('ix_waiting_phone'), table_name='waiting')
    op.drop_index(op.f('ix_waiting_id'), table_name='waiting')
    op.drop_table('waiting')
    # ### end Alembic commands ###
